n_channel: 3
n_classes: 10
image_size: 32
weight_decay: 0.0001
data_format: "channels_last"
batch_size: 128
valid_rate: 0.9
update_function: "momentum"

network_path: "src/config/networks/resnet56.yaml"
data_path: "data/CIFAR10_data"
seq: "cifar10-v5"

train_gpus: "0"
n_epoch: 200
